### ISSUE TITLE
Duplicate keys in `blueprints.yaml` resulting in Exception

### ISSUE THREAD

**Issue by NoNoNo** [stephan-strate/grav-plugin-logger-channels#5]
> PHP Fatal error:  Uncaught Symfony\Component\Yaml\Exception\ParseException: Duplicate key "min" detected at line 104 (near "min: 65535"). in vendor/symfony/yaml/Parser.php:342

## Duplicate key: `type: min`

https://github.com/stephan-strate/grav-plugin-logger-channels/blob/7ae1c792718c52ecbfffcfd93e597ed3b93e2f4a/blueprints.yaml#L103-L104

Should be:

```yaml
min: 1
max: 65535
```

## Duplicate key: `type: list`

https://github.com/stephan-strate/grav-plugin-logger-channels/blob/7ae1c792718c52ecbfffcfd93e597ed3b93e2f4a/blueprints.yaml#L112-L116

**Comment by stephan-strate** [comment]
Thanks for reporting.

Fixed by #6. Patch release will be released today.
